

insert into	PENSIOEN_REGELING (ID, JAARLIJKS_RENDEMENT_BELEGGINGEN,NAAM, PREMIE_PERCENTAGE, VOLTIJD_FRANCHISE)
values (1, 3, 'naam pensioen regeling 1', 1.657, 13785);

insert into	PENSIOEN_REGELING (ID, JAARLIJKS_RENDEMENT_BELEGGINGEN,NAAM, PREMIE_PERCENTAGE, VOLTIJD_FRANCHISE)
values (2, 3, 'naam pensioen regeling 2', 5, 15599);


insert into DEELNEMER (ADRES,DEELTIJD_PERCENTAGE,EINDDATUM_DIENST,EMAIL,GEBOORTEDATUM,HUIDIGE_WAARDE_BELEGGINGEN, JAARLIJKSE_PREMIE_STORTING_RESULTAAT,NAAM,REKENING,STARTDATUM_DIENST,VERWACHTE_WAARDE_PENSIOEN_RESULTAAT,VOLTIJDSALARIS,WOONPLAATS,PENSIOEN_REGELING_ID)
values ('adres', 100, '2028-01-01', 'email@email.com', '1980-01-01',100, 0, 'naam deelnemer 1','rekening1', '2010-01-01', 0, 40000, 'woonplaats', 1);

insert into DEELNEMER (ADRES,DEELTIJD_PERCENTAGE,EINDDATUM_DIENST,EMAIL,GEBOORTEDATUM,HUIDIGE_WAARDE_BELEGGINGEN, JAARLIJKSE_PREMIE_STORTING_RESULTAAT,NAAM,REKENING,STARTDATUM_DIENST,VERWACHTE_WAARDE_PENSIOEN_RESULTAAT,VOLTIJDSALARIS,WOONPLAATS,PENSIOEN_REGELING_ID)
values ('adres', 100, '2028-01-01', 'email@email.com', '1980-01-01',100, 0, 'naam deelnemer 2','rekening1', '2010-01-01', 0, 40000, 'woonplaats', 2);
